# Generated by Django 5.2.7 on 2025-10-30 12:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='identifier')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('color', models.CharField(default='#007bff', help_text='Hex color code', max_length=7, verbose_name='color')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='identifier')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='identifier')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_published', models.BooleanField(default=False, verbose_name='is published')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('excerpt', models.TextField(blank=True, help_text='Short description of the article', max_length=500, verbose_name='excerpt')),
                ('content', models.TextField(verbose_name='content')),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description (max 160 characters)', max_length=160, verbose_name='meta description')),
                ('meta_keywords', models.CharField(blank=True, help_text='SEO keywords separated by commas', max_length=255, verbose_name='meta keywords')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='articles/images/%Y/%m/', verbose_name='featured image')),
                ('featured_image_alt', models.CharField(blank=True, max_length=200, verbose_name='featured image alt text')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='view count')),
                ('is_featured', models.BooleanField(default=False, verbose_name='is featured')),
                ('order', models.IntegerField(default=0, help_text='Higher numbers appear first', verbose_name='order')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='main.category', verbose_name='category')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='main.tag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
                'ordering': ('-order', '-created_at'),
                'indexes': [models.Index(fields=['is_published', 'published_at'], name='main_articl_is_publ_8d5e90_idx'), models.Index(fields=['category', 'is_published'], name='main_articl_categor_321505_idx'), models.Index(fields=['author', 'is_published'], name='main_articl_author__b1fc9d_idx'), models.Index(fields=['is_featured', 'is_published'], name='main_articl_is_feat_f72b8c_idx')],
            },
        ),
    ]
